import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'
import type {
  CreateHarnessAccount,
  HarnessAccount,
  PatchHarnessAccount,
} from '@forge/protocol/accounts'
import type { HarnessConfig } from '@forge/protocol/config'

type Db = { prepare(sql: string): any }
type AccountRow = {
  id: string
  harness_key: string
  label: string
  kind: string
  home_path: string
  order_index: number
  disabled_at: number | null
  created_at: number
  last_used_at: number | null
  identity: string | null
  identity_checked_at: number | null
  label_auto_generated: number
  config: string | null
}

export const accountRoot = () =>
  resolve(
    process.env.FORGE_ACCOUNTS_DIR ?? join(homedir(), '.forge', 'accounts'),
  )
const toAccount = (row: AccountRow): HarnessAccount => ({
  id: row.id,
  harnessKey: row.harness_key,
  label: row.label,
  kind: row.kind,
  homePath: row.home_path,
  orderIndex: row.order_index,
  disabledAt: row.disabled_at,
  createdAt: row.created_at,
  lastUsedAt: row.last_used_at,
  identity: parseIdentity(row.identity),
  config: parseConfig(row.config),
})
function parseIdentity(value: string | null) {
  if (!value) return null
  try {
    const parsed = JSON.parse(value)
    return parsed && typeof parsed === 'object' ? parsed : null
  } catch {
    return null
  }
}
function parseConfig(value: string | null) {
  if (!value) return null
  try {
    const parsed = JSON.parse(value)
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed)
      ? parsed
      : {}
  } catch {
    return {}
  }
}
const newId = () => `acct_${crypto.randomUUID().replaceAll('-', '')}`

function assertManagedHome(homePath: string) {
  const root = accountRoot()
  const resolved = resolve(homePath)
  if (resolved !== root && !resolved.startsWith(`${root}/`))
    throw new Error('Account home is outside the accounts directory')
  return resolved
}

export class HarnessAccountStore {
  constructor(private readonly db: Db) {}

  list(harnessKey?: string) {
    const rows = harnessKey
      ? this.db
          .prepare(
            'SELECT * FROM harness_accounts WHERE harness_key = ? ORDER BY order_index, created_at',
          )
          .all(harnessKey)
      : this.db
          .prepare(
            'SELECT * FROM harness_accounts ORDER BY harness_key, order_index, created_at',
          )
          .all()
    return (rows as AccountRow[]).map(toAccount)
  }

  get(id: string) {
    const row = this.db
      .prepare('SELECT * FROM harness_accounts WHERE id = ?')
      .get(id) as AccountRow | undefined
    return row ? toAccount(row) : undefined
  }

  create(input: CreateHarnessAccount) {
    const id = newId()
    const now = Date.now()
    const homePath = join(accountRoot(), input.kind, id)
    mkdirSync(homePath, { recursive: true, mode: 0o700 })
    chmodSync(homePath, 0o700)
    this.db
      .prepare(
        `INSERT INTO harness_accounts
          (id, harness_key, label, kind, home_path, order_index, created_at, label_auto_generated, config)
         VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)`,
      )
      .run(
        id,
        input.harnessKey,
        input.label,
        input.kind,
        homePath,
        input.orderIndex ?? 0,
        now,
        input.config ? JSON.stringify(input.config) : null,
      )
    return this.get(id)!
  }

  patch(id: string, input: PatchHarnessAccount) {
    const current = this.get(id)
    if (!current) return undefined
    const disabledAt =
      input.disabled === undefined
        ? current.disabledAt
        : input.disabled
          ? (current.disabledAt ?? Date.now())
          : null
    this.db
      .prepare(
        'UPDATE harness_accounts SET label = ?, order_index = ?, disabled_at = ?, label_auto_generated = ?, config = ? WHERE id = ?',
      )
      .run(
        input.label ?? current.label,
        input.orderIndex ?? current.orderIndex,
        disabledAt,
        input.label === undefined ? (this.labelIsAutoGenerated(id) ? 1 : 0) : 0,
        input.config === undefined
          ? current.config
            ? JSON.stringify(current.config)
            : null
          : input.config
            ? JSON.stringify(input.config)
            : null,
        id,
      )
    return this.get(id)
  }

  saveIdentity(id: string, identity: HarnessAccount['identity']) {
    this.db
      .prepare(
        'UPDATE harness_accounts SET identity = ?, identity_checked_at = ? WHERE id = ?',
      )
      .run(identity ? JSON.stringify(identity) : null, Date.now(), id)
    return this.get(id)
  }

  identityCheckedAt(id: string) {
    const row = this.db
      .prepare('SELECT identity_checked_at FROM harness_accounts WHERE id = ?')
      .get(id) as { identity_checked_at: number | null } | undefined
    return row?.identity_checked_at ?? null
  }

  labelIsAutoGenerated(id: string) {
    const row = this.db
      .prepare('SELECT label_auto_generated FROM harness_accounts WHERE id = ?')
      .get(id) as { label_auto_generated: number } | undefined
    return row?.label_auto_generated === 1
  }

  rename(id: string, label: string) {
    return this.patch(id, { label })
  }

  reorder(id: string, orderIndex: number) {
    return this.patch(id, { orderIndex })
  }

  disable(id: string) {
    return this.patch(id, { disabled: true })
  }

  delete(id: string, removeHome = false) {
    const current = this.get(id)
    if (!current) return false
    this.db.prepare('DELETE FROM harness_accounts WHERE id = ?').run(id)
    if (removeHome)
      rmSync(assertManagedHome(current.homePath), {
        recursive: true,
        force: true,
      })
    return true
  }

  /** Wipes an account's home directory in place, keeping the account row. */
  resetHome(id: string) {
    const current = this.get(id)
    if (!current) return undefined
    rmSync(assertManagedHome(current.homePath), {
      recursive: true,
      force: true,
    })
    mkdirSync(current.homePath, { recursive: true, mode: 0o700 })
    chmodSync(current.homePath, 0o700)
    return current
  }
}

export const ACCOUNT_KINDS = [
  'claude',
  'codex',
  'kimi',
  'opencode',
  'grok',
  'pi',
] as const

/**
 * Derives the account kind a harness entry belongs to by token-matching the
 * key, command, and args. Harnesses with no managed-account support (gemini,
 * mock, custom PTY entries) return null and run on ambient credentials.
 */
export function accountKindForHarness(
  key: string,
  entry?: { command?: string; args?: string[] },
): string | null {
  const tokens = [key, entry?.command ?? '', ...(entry?.args ?? [])]
    .join(' ')
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean)
  for (const kind of [...ACCOUNT_KINDS].sort(
    (left, right) => right.length - left.length,
  )) {
    if (tokens.includes(kind)) return kind
  }
  return null
}

export function accountEnv(
  kind: string,
  homePath: string,
): Record<string, string> {
  switch (kind) {
    case 'claude':
      return { CLAUDE_CONFIG_DIR: homePath }
    case 'codex':
      return { CODEX_HOME: homePath }
    case 'kimi':
      return { KIMI_SHARE_DIR: homePath }
    case 'opencode':
      return {
        XDG_DATA_HOME: homePath,
        OPENCODE_DB: join(homePath, 'opencode', 'opencode.db'),
      }
    case 'grok':
      return { GROK_HOME: homePath }
    case 'pi':
      return {
        PI_CODING_AGENT_DIR: homePath,
        PI_CODING_AGENT_SESSION_DIR: join(homePath, 'sessions'),
      }
    default:
      return {}
  }
}

type AccountConfig = NonNullable<HarnessAccount['config']>

export function accountConfigOverlay(
  kind: string,
  homePath: string,
  config: AccountConfig | null | undefined,
): { env: Record<string, string>; args: string[] } {
  if (!config || Object.keys(config).length === 0) return { env: {}, args: [] }
  if (kind === 'grok')
    return {
      env: {},
      args: [
        ...(config.model ? ['--model', config.model] : []),
        ...(config.thinking ? ['--effort', config.thinking] : []),
      ],
    }
  if (kind === 'opencode' && (config.provider || config.model)) {
    const value: Record<string, unknown> = {}
    if (config.provider && config.model)
      value.model = `${config.provider}/${config.model}`
    if (config.provider && config.model && config.thinking)
      value.provider = {
        [config.provider]: {
          models: {
            [config.model]: { options: { reasoningEffort: config.thinking } },
          },
        },
      }
    return { env: { OPENCODE_CONFIG_CONTENT: JSON.stringify(value) }, args: [] }
  }
  if (kind === 'pi') {
    const settingsPath = join(homePath, 'settings.json')
    let settings: Record<string, unknown> = {}
    try {
      const parsed = JSON.parse(readFileSync(settingsPath, 'utf8'))
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed))
        settings = parsed
    } catch {}
    if (config.provider) settings.defaultProvider = config.provider
    if (config.model) settings.defaultModel = config.model
    if (config.thinking) settings.defaultThinkingLevel = config.thinking
    writeFileSync(settingsPath, JSON.stringify(settings))
    return {
      env: {},
      args: [
        ...(config.provider ? ['--provider', config.provider] : []),
        ...(config.model ? ['--model', config.model] : []),
        ...(config.thinking ? ['--thinking', config.thinking] : []),
      ],
    }
  }
  return { env: {}, args: [] }
}

export function deriveAccountHarness(
  entry: HarnessConfig,
  account: Pick<HarnessAccount, 'kind' | 'homePath' | 'config'>,
): HarnessConfig {
  const overlay = accountConfigOverlay(
    account.kind,
    account.homePath,
    account.config,
  )
  const args = [...entry.args]
  const stdioIndex = args.lastIndexOf('stdio')
  args.splice(stdioIndex < 0 ? args.length : stdioIndex, 0, ...overlay.args)
  return {
    ...entry,
    args,
    env: {
      ...entry.env,
      ...accountEnv(account.kind, account.homePath),
      ...overlay.env,
    },
  }
}

function credentialFiles(kind: string): string[] {
  switch (kind) {
    case 'claude':
      return ['.credentials.json', '.claude.json']
    case 'codex':
      return ['auth.json']
    case 'kimi':
      return ['credentials/kimi-code.json']
    case 'opencode':
      return ['opencode/auth.json']
    case 'grok':
    case 'pi':
      return ['auth.json']
    default:
      return []
  }
}

export function accountAuthenticated(kind: string, homePath: string) {
  if (kind === 'claude') {
    try {
      const credentials = JSON.parse(
        readFileSync(join(homePath, '.credentials.json'), 'utf8'),
      )
      return typeof credentials.claudeAiOauth?.accessToken === 'string'
    } catch {
      return false
    }
  }
  return credentialFiles(kind).some((file) => existsSync(join(homePath, file)))
}

/** Deletes just the credential files inside an account home, leaving the rest in place. */
export function clearAccountCredentials(kind: string, homePath: string) {
  assertManagedHome(homePath)
  for (const file of credentialFiles(kind))
    rmSync(join(homePath, file), { force: true })
}
